<?php
/**
 * Template part for displaying the pricing section
 *
 * @package Pchelka
 */

?>
<section class="pricing" id="pricing">
    <div class="container">
        <h2 class="section-title text-center">Прозрачное ценообразование</h2>
        <p class="section-subtitle text-center">Честные цены без скрытых платежей</p>
        <div class="pricing-tabs"><button class="pricing-tab active" data-category="consultations">Консультации</button><button class="pricing-tab" data-category="diagnostics">Диагностика</button><button class="pricing-tab" data-category="procedures">Процедуры</button><button class="pricing-tab" data-category="programs">Программы</button></div>
        <div class="pricing-content active" data-category="consultations"><div class="pricing-table"><div class="pricing-row"><div class="pricing-service"><h4>Прием терапевта (первичный)</h4><p>Осмотр, сбор анамнеза, назначение обследований</p></div><div class="pricing-price">2 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Прием терапевта (повторный)</h4><p>Контрольный осмотр, коррекция лечения</p></div><div class="pricing-price">2 000 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Прием кардиолога</h4><p>Консультация с ЭКГ и расшифровкой</p></div><div class="pricing-price">3 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Прием невролога</h4><p>Неврологический осмотр, назначение лечения</p></div><div class="pricing-price">3 000 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Прием эндокринолога</h4><p>Консультация по эндокринным заболеваниям</p></div><div class="pricing-price">3 200 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Прием педиатра</h4><p>Осмотр ребенка, консультация родителей</p></div><div class="pricing-price">2 800 ₽</div></div></div></div>
        <div class="pricing-content" data-category="diagnostics"><div class="pricing-table"><div class="pricing-row"><div class="pricing-service"><h4>ЭКГ (электрокардиограмма)</h4><p>12 отведений с расшифровкой</p></div><div class="pricing-price">1 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>УЗИ органов брюшной полости</h4><p>Печень, желчный пузырь, поджелудочная, селезенка</p></div><div class="pricing-price">3 000 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>УЗИ сердца (ЭхоКГ)</h4><p>С допплерографией и заключением кардиолога</p></div><div class="pricing-price">4 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Общий анализ крови</h4><p>Развернутый, результат в день обращения</p></div><div class="pricing-price">800 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Биохимический анализ крови</h4><p>Базовый профиль (12 показателей)</p></div><div class="pricing-price">2 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Рентгенография</h4><p>Цифровая, 1 проекция</p></div><div class="pricing-price">2 000 ₽</div></div></div></div>
        <div class="pricing-content" data-category="procedures"><div class="pricing-table"><div class="pricing-row"><div class="pricing-service"><h4>Внутривенная инъекция</h4><p>Без стоимости препарата</p></div><div class="pricing-price">500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Внутримышечная инъекция</h4><p>Без стоимости препарата</p></div><div class="pricing-price">300 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Капельница (инфузионная терапия)</h4><p>Без стоимости препаратов, до 400 мл</p></div><div class="pricing-price">1 500 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Забор крови из вены</h4><p>Для лабораторных исследований</p></div><div class="pricing-price">300 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Измерение артериального давления</h4><p>С консультацией медсестры</p></div><div class="pricing-price">200 ₽</div></div><div class="pricing-row"><div class="pricing-service"><h4>Перевязка</h4><p>Без стоимости материалов</p></div><div class="pricing-price">800 ₽</div></div></div></div>
        <div class="pricing-content" data-category="programs"><div class="pricing-packages"><div class="package-card"><div class="package-badge">Популярно</div><h3 class="package-title">Базовое обследование</h3><div class="package-price"><span class="price-value">12 000 ₽</span><span class="price-old">15 000 ₽</span></div><ul class="package-includes"><li>Прием терапевта</li><li>ЭКГ с расшифровкой</li><li>Общий анализ крови</li><li>Биохимический анализ крови</li><li>Общий анализ мочи</li><li>УЗИ органов брюшной полости</li></ul><button onclick="openAppointmentModal('basic')" class="btn btn-secondary btn-block">Записаться</button></div><div class="package-card package-card-featured"><div class="package-badge">Рекомендуем</div><h3 class="package-title">Комплексное обследование</h3><div class="package-price"><span class="price-value">25 000 ₽</span><span class="price-old">32 000 ₽</span></div><ul class="package-includes"><li>Все из базового пакета</li><li>Прием кардиолога</li><li>ЭхоКГ (УЗИ сердца)</li><li>УЗИ щитовидной железы</li><li>Гормоны щитовидной железы</li><li>Рентген грудной клетки</li><li>Консультация эндокринолога</li></ul><button onclick="openAppointmentModal('complex')" class="btn btn-primary btn-block">Записаться</button></div><div class="package-card"><div class="package-badge">Premium</div><h3 class="package-title">VIP Check-up</h3><div class="package-price"><span class="price-value">45 000 ₽</span><span class="price-old">60 000 ₽</span></div><ul class="package-includes"><li>Все из комплексного пакета</li><li>Прием невролога</li><li>МРТ головного мозга</li><li>Расширенный онкоскрининг</li><li>Генетическое тестирование</li><li>Консультация диетолога</li><li>Индивидуальная программа здоровья</li></ul><button onclick="openAppointmentModal('vip')" class="btn btn-secondary btn-block">Записаться</button></div></div></div>
        <div class="pricing-footer"><div class="pricing-calculator"><h3>Рассчитайте стоимость вашего обследования</h3><p>Выберите необходимые услуги и получите точную стоимость с учетом скидок</p><button onclick="openCalculatorModal()" class="btn btn-primary">Открыть калькулятор</button></div><div class="pricing-note"><p><strong>Важно:</strong> Цены актуальны на январь 2024 года. Для держателей карт лояльности действуют дополнительные скидки.</p><a href="#" onclick="downloadPriceList(); return false;" class="btn btn-outline">Скачать полный прайс-лист (PDF)</a></div></div>
    </div>
</section>