# Jekyll Configuration for Medical Clinic Documentation
title: Medical Clinic Website Documentation
email: zaebuntu@gmail.com
description: >-
  Interactive documentation and architecture overview for medical clinic website
  development project with online appointment booking system.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://medicine.zae.life" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (GitHub Pages supported plugins only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Kramdown configuration
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files that start with underscore
include:
  - _pages

# Sass configuration
sass:
  style: compressed
  sass_dir: _sass

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO settings
author: Medical Clinic Development Team
twitter:
  username: # Add if needed
facebook:
  app_id: # Add if needed
  publisher: # Add if needed

# Google Analytics (optional)
google_analytics: # Add GA tracking ID if needed

# Mermaid configuration (will be added via layout)
mermaid:
  enable: true
  theme: default